networks:
  inception:

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file: .env
    restart: always
    privileged: true
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    init: true
    healthcheck:
        test:		"mariadb-admin ping"
        interval:	5s
        timeout:	1m
        retries:	3
  nginx:
    container_name: nginx
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: always
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    init: true
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file: .env
    restart: always
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/wordpress
    init: true

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tchartie/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tchartie/data/wordpress