services:
  mariadb:
    container_name: mariadb
    build: requiremnents/mariadb
    env_file: .env
  nginx:
    container_name: nginx
    build: requiremnents/nginx
    env_file: .env
    ports: "443:443"
  wordpress:
    container_name: wordpress
    build: requiremnents/wordpress
    env_file: .env